name: send-message 
description: Send an alert to Telegram or Rocket Chat 
inputs:
  telegram_token:
    description: Telegram Bot Token (from @BotFather)
    default: ''
    required: false
  telegram_to:
    description: ID of the target chat (get using @getidsbot) 
    default: ''
    required: false
  rocket_chat_url:
    description: Rocket Chat URL
    default: ''
    required: false
  rocket_chat_token:
    description: Rocket Chat Token
    default: ''
    required: false
  rocket_chat_userID:
    description: Rocket Chat User ID
    default: ''
    required: false
  rocket_chat_target_chat:
    description: Rocket Chat Target Chat
    default: ''
    required: false
  telegram:
    description: Send message to Telegram
    default: 'false'
    required: false
  rocket_chat:
    description: Send message to Rocket Chat
    default: 'false'
    required: false
  pull_request_number:
    description: PR number to generate a PR link
    required: false
  repository_name:
    description: Repository name to generate a PR link
    required: false
  host:
    descipriotn: Host to generate a PR link
    required: false
  message_text:
    description: Message text
    required: true
outputs:
  success:
    description: Script result
    value: ${{ steps.script.outputs.result }}

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: pip3 install httpx
      shell: bash
    - name: run-script
      id: script
      env:
        INPUT_TELEGRAM_TOKEN: ${{ inputs.telegram_token }}
        INPUT_TELEGRAM_TO: ${{ inputs.telegram_to }}
        INPUT_ROCKET_CHAT_URL: ${{ inputs.rocket_chat_url }}
        INPUT_ROCKET_CHAT_TOKEN: ${{ inputs.rocket_chat_token }}
        INPUT_ROCKET_CHAT_USERID: ${{ inputs.rocket_chat_userID }}
        INPUT_ROCKET_CHAT_TARGET_CHAT: ${{ inputs.rocket_chat_target_chat }}
        INPUT_MESSAGE_TEXT: ${{ inputs.message_text }}
        INPUT_ROCKET_CHAT: ${{ inputs.rocket_chat }}
        INPUT_TELEGRAM: ${{ inputs.telegram }}
        INPUT_PULL_REQUEST_NUMBER: ${{ inputs.pull_request_number }}
        INPUT_REPOSITORY_NAME: ${{ inputs.repository_name }}
        INPUT_HOST: ${{ inputs.host }}
      run: |
        python3 ${{ github.action_path }}/message.py
      shell: bash
