name: send-message 
description: Send an alert to Telegram or Rocket Chat 
inputs:
  telegram-token:
    description: Telegram Bot Token (from @BotFather)
    required: false
  telegram-chat-id:
    description: ID of the target chat (get using @getidsbot) 
    required: false
  rocket-chat-url:
    description: Rocket Chat URL
    required: false
  rocket-chat-token:
    description: Rocket Chat Token
    required: false
  rocket-chat-userID:
    description: Rocket Chat User ID
    required: false
  rocket-chat-target-chat:
    description: Rocket Chat Target Chat
    required: false
  telegram:
    description: Send message to Telegram
    default: 'false'
    required: false
  rocket-chat:
    description: Send message to Rocket Chat
    default: 'false'
    required: false
  message-text:
    description: Message text
    required: true
# outputs:
#   success:
#     description: Script result
#     value: ${{ steps.script.outputs.result }}

runs:
  using: composite
  steps:
    # - name: Install Python
    #   uses: actions/setup-python@v4
    - name: Install dependencies
      run: pip3 install -r requirements.txt
      shell: bash
    - name: Pass inputs to shell
      run: echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: run-script
      id: script
      run: python3 message.py
      shell: bash
