name: Test
description: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-action:
    runs-on: macOS
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          telegram-token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          rocket-chat-url: ${{ secrets.ROCKET_CHAT_URL }}
          rocket-chat-token: ${{ secrets.ROCKET_CHAT_TOKEN }}
          rocket-chat-userID: ${{ secrets.ROCKET_CHAT_USERID }}
          rocket-chat-target-chat: ${{ secrets.ROCKET_CHAT_TARGET_CHAT }}
          telegram: 'true'
          rocket-chat: 'false'
          message-text: >
            ${{ format('{0} <b>Build: Messenger Action</b>\n- Build Number: {1}\n- Commit: <a href="{2}">{3}</a> by <b>{4}</b>\n{5}\n- {6}\n- Workflow Run: <a href="{7}">{8}</a>\n', job.status == 'success' ? '✅' : '🛑', github.run_number, github.event.head_commit.url, github.event.head_commit.message, github.event.head_commit.author.name, github.event.pull_request ? format('Pull Request: <a href="{0}">{1}</a>', github.event.pull_request.html_url, github.event.pull_request.title) : format('Branch: {0}', github.ref.replace('refs/heads/', '')), github.workflow, github.event.workflow_run.url, job.status) }}




