name: Test
description: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job1:
    runs-on: macOS
    steps:
      - run: echo "Job 1 succeeded"
  job2:
    runs-on: macOS
    steps:
      - run: echo "Job 2 succeeded"
  job3:
    runs-on: macOS
    steps:
      - run: echo "Job 3 succeeded"
  check:
    runs-on: macOS
    needs: [job1, job2, job3]
    steps:
      - run: |
          if [ "${{ jobs.job1.outcome }}" == "success" ] && \
             [ "${{ jobs.job2.outcome }}" == "success" ] && \
             [ "${{ jobs.job3.outcome }}" == "success" ]; then
              echo "All jobs succeeded"
              echo "::set-output name=jobs_success::true"
            else
              echo "One or more jobs failed"
              echo "::set-output name=jobs_success::false"
            fi
  test-action:
    runs-on: macOS
    if: always()
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          telegram-token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          rocket-chat-url: ${{ secrets.ROCKET_CHAT_URL }}
          rocket-chat-token: ${{ secrets.ROCKET_CHAT_TOKEN }}
          rocket-chat-userID: ${{ secrets.ROCKET_CHAT_USERID }}
          rocket-chat-target-chat: ${{ secrets.ROCKET_CHAT_TARGET_CHAT }}
          telegram: 'true'
          rocket-chat: 'true'
          message-text: |
            Build: <b>Messenger Action</b>
            - Build Number: ${{ github.run_number }}
            - Workflow Run: <a href="${{ github.event.workflow_run.url }}">${{ github.workflow }}</a>
            - ${{ needs.check.outputs.jobs_success == 'true' && '✅ All jobs succeeded' || '❌ One or more jobs failed' }}
            - Changelog: ${{ steps.changelog.outputs.output }}



