name: Test
description: Test
on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: macOS
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          telegram-token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          rocket-chat-url: ${{ secrets.ROCKET_CHAT_URL }}
          rocket-chat-token: ${{ secrets.ROCKET_CHAT_TOKEN }}
          rocket-chat-userID: ${{ secrets.ROCKET_CHAT_USERID }}
          rocket-chat-target-chat: ${{ secrets.ROCKET_CHAT_TARGET_CHAT }}
          telegram: 'true'
          rocket-chat: 'true'
          message-text: 'Test message'

