name: Test
description: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-action:
    runs-on: macOS
    if: always()
    steps:
      - uses: actions/checkout@v3
      - name: Generate changelog
        id: changelog
        uses: https://github.com/glebosotov/changelog-action@main
        with:
          gitea_token: ${{ secrets.GITEA_TOKEN }}
      - uses: ./
        with:
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram_to: ${{ secrets.TELEGRAM_CHAT_ID }}
          rocket_chat_url: ${{ secrets.ROCKET_CHAT_URL }}
          rocket_chat_token: ${{ secrets.ROCKET_CHAT_TOKEN }}
          rocket_chat_userID: ${{ secrets.ROCKET_CHAT_USERID }}
          rocket_chat_target_chat: ${{ secrets.ROCKET_CHAT_TARGET_CHAT }}
          telegram: 'true'
          rocket_chat: 'true'
          message_text: |
            Build: *Messenger Action*
            - Build Number: ${{ github.run_number }}
            - Run name: ${{ github.workflow }}
            - Changelog: ${{ steps.changelog.outputs.changelog }}
