name: Test
description: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-action:
    runs-on: macOS
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          telegram-token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          rocket-chat-url: ${{ secrets.ROCKET_CHAT_URL }}
          rocket-chat-token: ${{ secrets.ROCKET_CHAT_TOKEN }}
          rocket-chat-userID: ${{ secrets.ROCKET_CHAT_USERID }}
          rocket-chat-target-chat: ${{ secrets.ROCKET_CHAT_TARGET_CHAT }}
          telegram: 'true'
          rocket-chat: 'false'
          message-text: |
            ${{ format('{0} <b>Build: Messenger Action</b>', job.status == 'success' ? '✅' : '🛑') }}
            - Build Number: ${{ github.run_number }}
            - Commit: <a href="${{ github.event.head_commit.url }}">{{{{ github.event.head_commit.message }}}}</a> by <b>${{ github.event.head_commit.author.name }}</b>
            ${{ if github.event.pull_request }}
            - Pull Request: <a href="${{ github.event.pull_request.html_url }}">{{{{ github.event.pull_request.title }}}}</a>
            ${{ else }}
            - Branch: ${{ github.ref.replace('refs/heads/', '') }}
            ${{ end }}
            - Workflow Run: <a href="${{ github.event.workflow_run.url }}">{{{{ github.workflow }}}}</a>




