name: Test
description: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-action:
    runs-on: macOS
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          telegram-token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          rocket-chat-url: ${{ secrets.ROCKET_CHAT_URL }}
          rocket-chat-token: ${{ secrets.ROCKET_CHAT_TOKEN }}
          rocket-chat-userID: ${{ secrets.ROCKET_CHAT_USERID }}
          rocket-chat-target-chat: ${{ secrets.ROCKET_CHAT_TARGET_CHAT }}
          telegram: 'true'
          rocket-chat: 'false'
          message-text: |
            ${{ format('{0}\n- Build Number: {1}\n- Commit: <a href="{2}">{{{{{{{{ github.event.head_commit.message }}}}}}}}</a> by <b>{3}</b>\n{4}\n- {5}\n- Workflow Run: <a href="{6}">{{{{{{{{ github.workflow }}}}}}}}</a>\n', format('{0} <b>Build: Messenger Action</b>', job.status == 'success' && '✅' || '🛑'), github.run_number, github.event.head_commit.url, github.event.head_commit.author.name, github.event.pull_request && format('Pull Request: <a href="{0}">{{{{{{{{ github.event.pull_request.title }}}}}}}}</a>', github.event.pull_request.html_url) || format('Branch: {0}', github.ref.replace('refs/heads/', '')), github.event.workflow_run.url)) }}





